@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Jan 03 11:46:52 +0300 2021
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto bcb6bc46b6014e889f6115231eff3244 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot viterbi_encoder_tb_behav xil_defaultlib.viterbi_encoder_tb -log elaborate.log"
call xelab  -wto bcb6bc46b6014e889f6115231eff3244 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot viterbi_encoder_tb_behav xil_defaultlib.viterbi_encoder_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
